Repository ephemeraHQ/converse-app, pull requests merged in 2024-10, with the labels that each got.

#963 feat: add theme + start of design system + haptics
  App.tsx
  babel.config.js
  design-system/Hstack.tsx
  design-system/Pressable.tsx
  design-system/ScrollView.tsx
  design-system/Text/AnimatedText.tsx
  design-system/Text/Text.presets.ts
  design-system/Text/Text.props.ts
  design-system/Text/Text.styles.ts
  design-system/Text/Text.tsx
  design-system/Text/index.ts
  design-system/Title.tsx
  design-system/TouchableOpacity.tsx
  design-system/VStack.tsx
  i18n/i18n.ts
  theme/animations.ts
  theme/border-radius.ts
  theme/borders.ts
  theme/colors.ts
  theme/colorsDark.ts
  theme/index.ts
  theme/spacing.ts
  theme/timing.ts
  theme/typography.ts
  theme/useAppTheme.ts
  tsconfig.json
  utils/haptics.ts
Labels: dev only

#1007 fix: Group Invite screen on iPad
  screens/Navigation/SplitScreenNavigation/SplitRightStackNavigation.tsx
Labels: 2.0.6

#999 feat: Show Profile info in join requests
  components/Avatar.tsx
  containers/GroupPendingRequestsTable.tsx
  hooks/usePreferredName.ts
  hooks/usePreferredNames.ts
  hooks/useProfileSocials.ts
  hooks/useProfilesSocials.ts
  i18n/translations/en.ts
  package.json
  queries/useProfileSocialsQuery.ts
  yarn.lock
Labels: 2.0.7

#1018 fix: Android Push Notification parsing
  android/app/src/main/java/com/converse/dev/PushNotificationsService.kt
Labels: 2.0.7

#984 feat: Android Variants
  .github/workflows/build-app-release.yml
  .github/workflows/build-internal.yml
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/google-services.json
  android/app/src/main/java/com/converse/AsyncStorage.kt
  android/app/src/main/java/com/converse/BackendApi.kt
  android/app/src/main/java/com/converse/Datatypes.kt
  android/app/src/main/java/com/converse/Keychain.kt
  android/app/src/main/java/com/converse/MainActivity.kt
  android/app/src/main/java/com/converse/MainApplication.kt
  android/app/src/main/java/com/converse/MessageNotification.kt
  android/app/src/main/java/com/converse/Mmkv.kt
  android/app/src/main/java/com/converse/NotificationParser.kt
  android/app/src/main/java/com/converse/NotificationUtils.kt
  android/app/src/main/java/com/converse/Profile.kt
  android/app/src/main/java/com/converse/PushNotificationsService.kt
  android/app/src/main/java/com/converse/Sentry.kt
  android/app/src/main/java/com/converse/Spam.kt
  android/app/src/main/java/com/converse/Sqlite.kt
  android/app/src/main/java/com/converse/Utils.kt
  android/app/src/main/java/com/converse/xmtp/Client.kt
  android/app/src/main/java/com/converse/xmtp/Conversations.kt
  android/app/src/main/java/com/converse/xmtp/Messages.kt
  android/app/src/main/res/values/strings.xml
  android/app/src/preview/AndroidManifest.xml
  android/app/src/preview/google-services.json
  android/app/src/preview/res/values/strings.xml
  android/app/src/prod/AndroidManifest.xml
  android/app/src/prod/google-services.json
  android/app/src/prod/res/values/strings.xml
  eas.json
  package.json
  scripts/build/android/preview.js
  scripts/build/android/production.js
  scripts/build/android/utils.js
  scripts/build/build.js
  scripts/build/update.js
Labels: 2.0.8

#1066 fix: Repeated messages showing as scaled and lower opacity
  components/Chat/Message/MessageActions.tsx
Labels: 2.0.7

#1067 fix: Render Frame on initial send
  components/Chat/Chat.tsx
  components/Chat/Frame/FramePreview.tsx
  components/Chat/Message/Message.tsx
  components/Chat/Message/MessageActions.tsx
  utils/frames.ts
Labels: 2.0.7

#1084 fix: URL Crash
  components/Chat/Chat.tsx
  components/Chat/Message/Message.tsx
  utils/messageContent.ts
Labels: 2.0.7

#1036 fix: Xmtp Engine Rerenders, Race Conditions, Crashes
  App.tsx
  App.web.tsx
  components/ExternalWalletPicker.tsx
  components/XmtpEngine.tsx
  data/db/index.ts
  data/store/appStore.ts
  utils/alert.ts
  utils/appState/appStateIsBlurred.ts
  utils/appState/waitUntilAppActive.ts
Labels: 2.0.8

#1137 feat: design system icon
  .eslintrc.json
  adr/adr.001.folder and file structure/example composite component structure.md
  components/Chat/ActionButton.tsx
  components/Picto/Picto.ios.tsx
  components/Picto/Picto.tsx
  components/Picto/Picto.types.ts
  components/Picto/index.ts
  components/PictoTitleSubtitle.tsx
  components/TableView/TableViewImage.tsx
  components/__tests__/__snapshots__/Button.test.tsx.snap
  design-system/Button/Button.props.ts
  design-system/Button/Button.tsx
  design-system/Header/Header.tsx
  design-system/Header/HeaderAction.tsx
  design-system/Icon/Icon.android.tsx
  design-system/Icon/Icon.tsx
  design-system/Icon/Icon.types.ts
  design-system/IconButton/IconButton.props.ts
  features/onboarding/Privy/PrivyPhoneEntry.tsx
  package.json
  screens/Navigation/ConversationListNav.ios.tsx
  styles/sizes/index.ts
  theme/icon.ts
  yarn.lock
Labels: 2.0.8
